version: "3.3"


volumes:
  pgdata:


services:

  pgdb:
    image: postgres:11

    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency

    volumes:
      - pgdata:/var/lib/postgresql

    ports:
      - "15432:5432"

  exc_app:
    image: back/exc_app

    build:
      context: ./back
      dockerfile: ./Dockerfile

    network_mode: host
    ports:
      - "5000:5000"
    expose:
      - 5000

    depends_on:
      - pgdb
