version: "3.3"

services:

  pgdb:
    image: postgres:11

    restart: always

    environment:
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_DB=currency

    ports:
      - "5433:5433"
    expose:
      - 5433

  exc_app:
    image: back/exc_app

    build:
      context: ./back
      dockerfile: ./Dockerfile

    network_mode: host
    ports:
      - "5000:5000"
    expose:
      - 5000

    depends_on:
      - pgdb
