"""
Initial migration

Revision ID: e8affcefc4c6
Revises: 
Create Date: 2021-09-26 22:37:01.119438
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.database.models.types import CURRENCY


# revision identifiers, used by Alembic.
revision = 'e8affcefc4c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'history',
        sa.Column('code', CURRENCY(length=3), nullable=False),
        sa.Column('date', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('value', sa.REAL(), nullable=True),
        sa.PrimaryKeyConstraint('code', 'date'),
        schema='currency'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        'history',
        schema='currency'
    )
    # ### end Alembic commands ###
